Vagrant.configure("2") do |config|  
  config.vm.box = "Test"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
 
  config.vm.define :TXDB01 do |txdb01| 
    txdb01.vm.hostname = "TXDB01"
    txdb01.vm.network :private_network, ip: "192.168.10.30"
    txdb01.vm.network :forwarded_port, host:225 , guest:22    
    txdb01.vm.provision :shell, :path => "bootstraptxdb01.sh"

   
  end
   
end
