Vagrant.configure("2") do |config|  
  config.vm.box = "Test"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
 
  config.vm.define :NFS do |nfs| 
    nfs.vm.hostname = "NFS"
    nfs.vm.network :private_network, ip: "192.168.10.2"
    nfs.vm.network :forwarded_port, host:21, guest:21
    nfs.vm.network :forwarded_port, host:445 , guest:445
    nfs.vm.provision :shell, :path => "bootstrapnfs"
   
  end
  
end
