Vagrant.configure("2") do |config|  
  config.vm.box = "Test"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  
 config.vm.define :tx do |txw| 
    txw.vm.hostname = "TXW02"
    txw.vm.network :private_network, ip: "192.168.10.12"
    txw.vm.network :forwarded_port, host:82, guest:80
    txw.vm.network :forwarded_port, host:226 , guest:22
    txw.vm.network :forwarded_port, host:3389 , guest:3389
    txw.vm.provision :shell, :path => "bootstraptxw02.sh"
   
  end
  
end
