Vagrant.configure("2") do |config|  
  config.vm.box = "Test"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
 
  config.vm.define :vmwww do |www| 
    www.vm.hostname = "VMwww"
    www.vm.network :forwarded_port, host:81, guest:81
    www.vm.network :forwarded_port, host:223 , guest:22
    www.vm.provision :shell, :path => "bootstrapWWW.sh"
   
  end
  
end
